Metrics/LineLength:
  Max: 99

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/AsciiComments:
  Exclude:
    - '**/*'

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'app/helpers/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
